name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Test with pytest
      run: pytest
    
    
    - name: Costruir imagen de docker
      run: docker build -t ghcr.io/danpzZz/landing:1.0.0
    
    - name: Login en GitHub Container Registry
      run: echo "${{ secrets.GHCR_PATH }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Publicar la imagen creada
      run: docker push ghcr.io/danpzZz/landing:1.0.0

     - name: 🧾 Mostrar variables básicas (solo locales, no secretos)
      run: |
        echo "Probando conexión SSH con:"
        echo "Host: ${{ secrets.GHCR_PATH }}"
        echo "Usuario: ${{ secrets.GHCR_USER }}"
        echo "Puerto: ${{ secrets.GHCR_PORTUPS }}"
        echo "Password: ${{ secrets.GHCR_PASSWORD }}"
    - name: 🧪 Probar conexión SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.GHCR_PATH }}
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_PASSWORD }}
        port: ${{ secrets.GHCR_PORTUPS }}
        script: |
          echo "✅ Conexión exitosa desde GitHub Actions"
          hostname
          whoami
          uptime